# AppSynergy Linux — drop into /etc/pacman.conf.d/ or Include from pacman.conf
[appsynergy]
SigLevel = Optional TrustAll
Server = https://git.appsynergy.io/api/packages/imabee/generic/appsynergy-repo/x86_64
